//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realmeye.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Realmeye.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Items&gt;
        ///  &lt;Item name=&quot;Potion of Attack&quot;&gt;
        ///    &lt;Abbr&gt;atk&lt;/Abbr&gt;
        ///    &lt;Abbr&gt;att&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Defense&quot;&gt;
        ///    &lt;Abbr&gt;def&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Speed&quot;&gt;
        ///    &lt;Abbr&gt;spd&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Vitality&quot;&gt;
        ///    &lt;Abbr&gt;vit&lt;/Abbr&gt;
        ///    &lt;Abbr&gt;vita&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Wisdom&quot;&gt;
        ///    &lt;Abbr&gt;wis&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Dexterity&quot;&gt;
        ///    &lt;Abbr&gt;dex&lt;/Abbr&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item name=&quot;Potion of Life&quot;&gt;
        ///    &lt;Abbr&gt;life&lt;/Abb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemAbbreviations {
            get {
                return ResourceManager.GetString("ItemAbbreviations", resourceCulture);
            }
        }
    }
}
