//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LootHelper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class LootHelperConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static LootHelperConfig defaultInstance = ((LootHelperConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LootHelperConfig())));
        
        public static LootHelperConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootNotifications {
            get {
                return ((bool)(this["LootNotifications"]));
            }
            set {
                this["LootNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoot {
            get {
                return ((bool)(this["AutoLoot"]));
            }
            set {
                this["AutoLoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Health Potion, Magic Potion, Potion of Life, Potion of Mana, Potion of Dexterity," +
            " Potion of Vitality, Potion of Defense, Potion of Speed, Potion of Wisdom, Potio" +
            "n of Attack")]
        public string AutoLootList {
            get {
                return ((string)(this["AutoLootList"]));
            }
            set {
                this["AutoLootList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootQuests {
            get {
                return ((bool)(this["LootQuests"]));
            }
            set {
                this["LootQuests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color NotificationColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationColor"]));
            }
            set {
                this["NotificationColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal, Purple, Egg, Blue, Cyan, White, Red")]
        public string LootBags {
            get {
                return ((string)(this["LootBags"]));
            }
            set {
                this["LootBags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue, Cyan, White, Red")]
        public string NotifBags {
            get {
                return ((string)(this["NotifBags"]));
            }
            set {
                this["NotifBags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte AutoLootWeaponTier {
            get {
                return ((byte)(this["AutoLootWeaponTier"]));
            }
            set {
                this["AutoLootWeaponTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte AutoLootArmorTier {
            get {
                return ((byte)(this["AutoLootArmorTier"]));
            }
            set {
                this["AutoLootArmorTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte AutoLootAbilityTier {
            get {
                return ((byte)(this["AutoLootAbilityTier"]));
            }
            set {
                this["AutoLootAbilityTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte AutoLootRingTier {
            get {
                return ((byte)(this["AutoLootRingTier"]));
            }
            set {
                this["AutoLootRingTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte AutoLootEggTier {
            get {
                return ((byte)(this["AutoLootEggTier"]));
            }
            set {
                this["AutoLootEggTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue, Cyan, White")]
        public string QuestBags {
            get {
                return ((string)(this["QuestBags"]));
            }
            set {
                this["QuestBags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int LootSpeed {
            get {
                return ((int)(this["LootSpeed"]));
            }
            set {
                this["LootSpeed"] = value;
            }
        }
    }
}
